spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pickfolio_auth
    username: pickfolio_user
    password: pickfolio_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  accessTokenSecret: ${JWT_SECRET:defaultSecret}
  accessTokenExpiryTime: 600000 # in milliseconds (10 minutes)
  refreshTokenSecret: ${JWT_REFRESH_SECRET:defaultRefreshSecret}
  refreshTokenExpiryTime: 604800000  # in milliseconds (7days)